[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blockingqueue = "0.1.1"

[[bin]]
name = "crawler"
path = "src/main.rs"
