[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "*"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "indexer"
path = "src/main.rs"
